events {
    worker_connections 1024;
}

http {

    upstream checkout_service {
        server checkout:3002;
    }

    upstream user_service {
        server user:3001;
    }


    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /checkout/ {
            proxy_pass http://checkout_service;
        }

        location /user/ {
            proxy_pass http://user_service;
        }
}
}
        # location /something {
        #     return 307 ./user
        # } it use to redirect