events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=checkout:10m rate=5r/m;
    limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;
    limit_conn_zone $binary_remote_addr zone=connc_lm:10m;


    upstream checkout_service {
        server checkout:3002;
    }
    upstream user_service {
        server user:3001;
    }


    server {

        listen 80;


        location /checkout {
            limit_conn connc_lm 2;
            limit_req zone=checkout;
            proxy_pass http://checkout_service/;
        }

        location /user/ {
            limit_req zone=login;
            limit_conn connc_lm 2;
            proxy_pass http://user_service/;
        }
    }

}

# location /something {
#     return 307 ./user
# } it use to redirect
# location / {
#     root /usr/share/nginx/html;
#     index index.html;
# }