events {
    worker_connections 1024;
}

http {

    upstream checkout_service {
        server checkout:3002;
    }

    upstream user_service {
        server user:3001;
    }

    server {
        listen 80;

        location /checkout/ {
            proxy_pass http://checkout_service;
        }

        location /user/ {
            proxy_pass http://user_service;
        }

    }
}